package dev.marrowseal.wardbound;

/**
 * Every dimension is mapped to one of these in the config file.
 */
public enum MinigameType {
    /** Rotating drum, strike each pin as the pick sweeps past it. */
    DRUM("drum", 1.00f),
    /** Bouncing marker on a bar, stop it inside the shrinking target zone. */
    TIMING("timing", 1.00f),
    /** Simon-says rune sequence, repeat what flashed. */
    MEMORY("memory", 1.05f),
    /** Reaction grid, click the glowing runes before they fade. */
    RUNES("runes", 1.00f),
    /** Three concentric glyph rings, lock each one against a fixed index mark. */
    CIPHER("cipher", 1.15f),
    /** Hold to build pressure, release inside the safe band. */
    PRESSURE("pressure", 1.05f),
    /** Match a humming waveform with the mouse, then lock it in. */
    RESONANCE("resonance", 1.10f),
    /** Rhythm lane, strike each mark as it crosses the line. */
    PULSE("pulse", 1.30f),
    /** Hold a tipping beam steady long enough for the bolt to seat. */
    BALANCE("balance", 1.25f),
    /** Retrace a line drawn between scattered stars. */
    CONSTELLATION("constellation", 1.15f),
    /** Pick the sigil facing the same way as the one on the lid. */
    MIRROR("mirror", 1.00f),
    /**
     * A pin tumbler cylinder in cutaway, picked one pin at a time in order.
     * Pays well: every pin is a separate hold-and-release that can overset, and
     * the tension wrench is running down the whole time.
     */
    KEYWAY("keyway", 1.20f),
    /**
     * A combination of sigil wheels, opened by deduction rather than by
     * reaction. Pays well because a life buys only a fresh set of attempts
     * against the same combination, so the lock cannot be brute forced past.
     */
    AUGURY("augury", 1.25f),
    /**
     * A ring of nodes struck in order by a sweeping needle. The ring is still
     * for the first two, then orbits and keeps gaining speed. Pays the most in
     * the mod because the last node on a full ring is genuinely hard.
     */
    GYRE("gyre", 1.35f),
    /**
     * A bowl of something dark with shapes moving under the surface. The only
     * lock in the mod that charges for its own information: seeing costs the
     * resource, so most of the play happens blind.
     */
    VESSEL("vessel", 1.30f),
    /**
     * A counterweight to steer and a ratchet to strike, at the same time, with
     * the two coupled so that succeeding at either makes the other harder. The
     * only lock here that asks for two kinds of attention at once, and the best
     * paid for that reason.
     */
    YOKE("yoke", 1.40f),
    /**
     * A mossy stone door with channels cut through it and something growing
     * along them. The only lock here that is spatial planning rather than
     * reaction, memory or inference.
     */
    ROOTWAY("rootway", 1.30f),
    /**
     * A black stone logic lattice. Pressing one seal changes a small, visible
     * neighbourhood of other seals; the board is generated by applying a known
     * solution, so every state is guaranteed solvable. Pure logic rather than
     * reaction, memory, rhythm or path finding.
     */
    LATTICE("lattice", 1.18f),
    /**
     * Four broken fragments of one impossible seal move at different parallax
     * depths. The player moves the cursor until the fragments occupy the same
     * place, then commits. Visual spatial alignment rather than timing, memory,
     * rhythm, path finding or the lattice's discrete logic.
     */
    PARALLAX("parallax", 1.16f),
    /**
     * A six-rune braid tied across a stone tablet. Each click swaps a pair of
     * adjacent runes; the board is scrambled from the answer by a legal list of
     * swaps, so replaying them in reverse always untangles the braid. A planning
     * puzzle with a heavy runic presentation rather than a timing or memory test.
     */
    RUNEBRAID("runebraid", 1.19f),
    /**
     * Six rune-shards form a two-by-three tablet. Each shard can be rotated;
     * neighbouring edge marks and the dead outer border must all agree. The
     * starting board is made by applying legal rotations to a solved tablet, so
     * every puzzle has a guaranteed path home.
     */
    SHARDSONG("shardsong", 1.20f),
    /**
     * A runic stepping board. The current stone names the exact distance of the
     * next jump; choose one legal destination and walk the sequence to the eye.
     * Spatial planning and route commitment rather than timing, rhythm, memory
     * or local tile matching.
     */
    VEILSTEP("veilstep", 1.22f),
    /**
     * Three black-glass measures. Pick a source and a destination; the source
     * pours until it empties or the destination is full. Reach the inscribed
     * amount. A classical measure/transfer logic puzzle, distinct from the
     * mod's timing, route, tile and sequence games.
     */
    BLACK_MEASURE("measure", 1.21f),
    /**
     * A singular ward: an adaptive eight-to-thirteen-passage final examination
     * built only for the rarest Cthulhu encounter. Its seeded route samples the
     * 26 ordinary disciplines, anchors observed weakness/strength, and always
     * closes with the Final Mouth.
     */
    CTHULHUS_GAME("cthulhus_game", 1.85f),
    /**
     * Four lines of a forbidden inscription obey one hidden grammar. The last
     * line is partly redacted; infer the transformation used by the witness
     * lines and restore the missing runes. Pattern-language deduction rather
     * than reaction, memory playback, route solving or local tile logic.
     * Appended after existing values so packet ordinals remain stable.
     */
    EPITAPH("epitaph", 1.28f),
    /**
     * Four occult rings share their motion through visible gear links. Turning one ring
     * moves another, so the player must reason about a coupled state rather than chase
     * an indicator. Generated only from legal moves and solved against the exact 8^4
     * state graph, guaranteeing a route back to the upper meridian.
     */
    ORRERY("orrery", 1.27f),
    /**
     * Six witnesses must be placed in one legal procession from relational testimony.
     * The clue generator enumerates every one of the 720 permutations and refuses any
     * clue set that leaves multiple answers, making this a true constraint puzzle rather
     * than a hidden-order guessing game.
     */
    PROCESSION("procession", 1.29f);

    /**
     * New entries must be appended, never inserted: the ordinal is what travels to the client in
     * {@code OpenMinigamePacket}, so reordering this enum would open the wrong lock.
     */

    public final String id;

    /**
     * How much this lock pays relative to the others. The four original games are all reflex or
     * memory tests of about the same weight; the newer ones ask for more. A rhythm run is a dozen
     * separate presses each of which can end you, so beating one is worth thirty percent more than
     * seating six pins.
     */
    public final float reward;

    MinigameType(String id, float reward) {
        this.id = id;
        this.reward = reward;
    }

    public static MinigameType byId(String s, MinigameType fallback) {
        if (s == null) return fallback;
        // The dial used to be called "lockpick", which became confusing once an
        // actual lockpicking game existed. Old config files still say it.
        if (s.equalsIgnoreCase("lockpick")) return DRUM;
        if (s.equalsIgnoreCase("black_lattice") || s.equalsIgnoreCase("blacklattice")) return LATTICE;
        if (s.equalsIgnoreCase("black_measure") || s.equalsIgnoreCase("blackmeasure")) return BLACK_MEASURE;
        for (MinigameType t : values()) {
            if (t.id.equalsIgnoreCase(s)) return t;
        }
        return fallback;
    }

    public static MinigameType byOrdinal(int i) {
        MinigameType[] v = values();
        return (i >= 0 && i < v.length) ? v[i] : DRUM;
    }
}
